theme: jekyll-theme-cayman
title: The MeToo movement: a turning point in the liberation of the women voices in the media?
Description: A Data Analysis project conducted on a database of newspaper citations between 2015 and 2020.
